service: upload-trigger-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    basePath: ./
    API_ENDPOINT: ${env:API_ENDPOINT}
    TEMP_S3_BUCKET_NAME: ${env:TEMP_S3_BUCKET_NAME}
    MY_AWS_REGION: ${env:MY_AWS_REGION}
    MY_AWS_ACCESS_KEY_ID: ${env:MY_AWS_ACCESS_KEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${env:MY_AWS_SECRET_ACCESS_KEY}
    DDB_TABLE_NAME: ${env:DDB_TABLE_NAME}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true

functions:
  api:
    handler: index.handler
    events:
      - s3:
          bucket: my-name-is-karan-thakur
          event: s3:ObjectCreated:*
          existing: true